export const nowplaying = {
    "dates": {
      "maximum": "2024-05-08",
      "minimum": "2024-03-27"
    },
    "page": 1,
    "results": [
      {
        "adult": false,
        "backdrop_path": "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
        "genre_ids": [28, 878, 12],
        "id": 823464,
        "original_language": "en",
        "original_title": "Godzilla x Kong: The New Empire",
        "overview": "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
        "popularity": 1818.259,
        "poster_path": "/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
        "release_date": "2024-03-27",
        "title": "Godzilla x Kong: The New Empire",
        "video": false,
        "vote_average": 6.514,
        "vote_count": 909
      },
      {
        "adult": false,
        "backdrop_path": "/kYgQzzjNis5jJalYtIHgrom0gOx.jpg",
        "genre_ids": [16, 28, 10751, 35, 14],
        "id": 1011985,
        "original_language": "en",
        "original_title": "Kung Fu Panda 4",
        "overview": "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
        "popularity": 1230.013,
        "poster_path": "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
        "release_date": "2024-04-10",
        "title": "Kung Fu Panda 4",
        "video": false,
        "vote_average": 7.1,
        "vote_count": 1474
      },
      {
        "adult": false,
        "backdrop_path": "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
        "genre_ids": [18, 12],
        "id": 618588,
        "original_language": "en",
        "original_title": "Arthur the King",
        "overview": "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
        "popularity": 651.969,
        "poster_path": "/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg",
        "release_date": "2024-04-17",
        "title": "Arthur the King",
        "video": false,
        "vote_average": 6.885,
        "vote_count": 91
      },
      {
        "adult": false,
        "backdrop_path": "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
        "genre_ids": [878, 12, 28],
        "id": 653346,
        "original_language": "en",
        "original_title": "Kingdom of the Planet of the Apes",
        "overview": "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
        "popularity": 686.196,
        "poster_path": "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
        "release_date": "2024-05-08",
        "title": "Kingdom of the Planet of the Apes",
        "video": false,
        "vote_average": 7.1,
        "vote_count": 8
      },
      {
        "adult": false,
        "backdrop_path": "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
        "genre_ids": [27],
        "id": 938614,
        "original_language": "en",
        "original_title": "Late Night with the Devil",
        "overview": "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
        "popularity": 394.054,
        "poster_path": "/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg",
        "release_date": "2024-05-08",
        "title": "Late Night with the Devil",
        "video": false,
        "vote_average": 7.376,
        "vote_count": 274
      },
      {
        "adult": false,
        "backdrop_path": "/bxmiZSQhQ581Y3vbEgpTtmEjt67.jpg",
        "genre_ids": [18, 10749],
        "id": 937287,
        "original_language": "en",
        "original_title": "Challengers",
        "overview": "Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a \"Challenger\" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi's former boyfriend.",
        "popularity": 392.576,
        "poster_path": "/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
        "release_date": "2024-04-24",
        "title": "Challengers",
        "video": false,
        "vote_average": 7.451,
        "vote_count": 316
      },
      {
        "adult": false,
        "backdrop_path": "/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg",
        "genre_ids": [28, 35],
        "id": 746036,
        "original_language": "en",
        "original_title": "The Fall Guy",
        "overview": "Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.",
        "popularity": 358.15,
        "poster_path": "/e7olqFmzcIX5c23kX4zSmLPJi8c.jpg",
        "release_date": "2024-05-01",
        "title": "The Fall Guy",
        "video": false,
        "vote_average": 7.544,
        "vote_count": 137
      },
      {
        "adult": false,
        "backdrop_path": "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
        "genre_ids": [28, 53, 18],
        "id": 866398,
        "original_language": "en",
        "original_title": "The Beekeeper",
        "overview": "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
        "popularity": 315.332,
        "poster_path": "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
        "release_date": "2024-04-03",
        "title": "The Beekeeper",
        "video": false,
        "vote_average": 7.437,
        "vote_count": 2222
      },
      {
        "adult": false,
        "backdrop_path": "/5cCfqeUH2f5Gnu7Lh9xepY9TB6x.jpg",
        "genre_ids": [14, 12, 35],
        "id": 967847,
        "original_language": "en",
        "original_title": "Ghostbusters: Frozen Empire",
        "overview": "The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who've developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
        "popularity": 256.112,
        "poster_path": "/6faYaQyiBPhqAizldJKq21mIVaE.jpg",
        "release_date": "2024-04-17",
        "title": "Ghostbusters: Frozen Empire",
        "video": false,
        "vote_average": 6.385,
        "vote_count": 366
      },
      {
        "adult": false,
        "backdrop_path": "/mIBG74mhGEJnBubhYLkCtvplcNr.jpg",
        "genre_ids": [27],
        "id": 437342,
        "original_language": "en",
        "original_title": "The First Omen",
        "overview": "When a young American woman is sent to Rome to begin a life of service to the church, she encounters a darkness that causes her to question her own faith and uncovers a terrifying conspiracy that hopes to bring about the birth of evil incarnate.",
        "popularity": 268.506,
        "poster_path": "/cIzk6GhxEZuweekGFXWEoAyuaMX.jpg",
        "release_date": "2024-04-03",
        "title": "The First Omen",
        "video": false,
        "vote_average": 6.613,
        "vote_count": 133
      },
      {
        "adult": false,
        "backdrop_path": "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
        "genre_ids": [18, 80],
        "id": 278,
        "original_language": "en",
        "original_title": "The Shawshank Redemption",
        "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        "popularity": 139.969,
        "poster_path": "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
        "release_date": "1995-01-28",
        "title": "The Shawshank Redemption",
        "video": false,
        "vote_average": 8.704,
        "vote_count": 26085
      },
      {
        "adult": false,
        "backdrop_path": "/mO9oOVXM8tTlC11VFM4FBBNnL3f.jpg",
        "genre_ids": [80, 28, 18],
        "id": 1017163,
        "original_language": "ko",
        "original_title": "범죄도시 4",
        "overview": "'Monster Cop' Ma Seok-do investigates an illegal online gambling business led by a former STS Baek and an IT genius CEO Chang. Ma proposes an unexpected alliance to Jang and begins hunting down the criminals.",
        "popularity": 110.476,
        "poster_path": "/yk38mNoJpsswmk9o7i7eLhO4mc.jpg",
        "release_date": "2024-04-24",
        "title": "The Roundup: Punishment",
        "video": false,
        "vote_average": 8.3,
        "vote_count": 5
      },
      {
        "adult": false,
        "backdrop_path": "/j11RoLbvHGmJsBHcKqvbZxc5drh.jpg",
        "genre_ids": [18, 28, 53],
        "id": 1053592,
        "original_language": "es",
        "original_title": "Todos los nombres de Dios",
        "overview": "After being implicated in a terrorist attack, Santi, a taxi driver, is taken hostage by one of the perpetrators.",
        "popularity": 71.974,
        "poster_path": "/n15gfcgwV0LVPSobrayZcFHcwN6.jpg",
        "release_date": "2024-04-17",
        "title": "All the Names of God",
        "video": false,
        "vote_average": 6.448,
        "vote_count": 87
      },
      {
        "adult": false,
        "backdrop_path": "/39bnNb5vty4Iy1koPcJMY625ga9.jpg",
        "genre_ids": [12, 35, 14, 18],
        "id": 837335,
        "original_language": "it",
        "original_title": "La chimera",
        "overview": "Just out of jail, crumpled English archaeologist Arthur reconnects with his wayward crew of tombaroli accomplices – a happy-go-lucky collective of itinerant grave-robbers who survive by looting Etruscan tombs and fencing the ancient treasures they dig up.",
        "popularity": 61.844,
        "poster_path": "/lDaUha09CumsoSAt9MIRbS9WBNH.jpg",
        "release_date": "2024-04-03",
        "title": "La Chimera",
        "video": false,
        "vote_average": 7.509,
        "vote_count": 220
      },
      {
        "adult": false,
        "backdrop_path": "/yvotjJ9nKlPKiwc8PtktIjRCkof.jpg",
        "genre_ids": [18, 36, 10749],
        "id": 921452,
        "original_language": "fr",
        "original_title": "Jeanne du Barry",
        "overview": "The life of Jeanne Bécu, who was born as the illegitimate daughter of an impoverished seamstress in 1743 and went on to rise through the Court of Louis XV to become his last official mistress.",
        "popularity": 39.629,
        "poster_path": "/o4WMgW6BJw5Tbj0dK3DJBVYku8Y.jpg",
        "release_date": "2024-04-03",
        "title": "Jeanne du Barry",
        "video": false,
        "vote_average": 6.979,
        "vote_count": 362
      },
      {
        "adult": false,
        "backdrop_path": "/9hTA1r7afRmy08SwElnYSgKidG4.jpg",
        "genre_ids": [18, 53],
        "id": 758679,
        "original_language": "en",
        "original_title": "Mothers' Instinct",
        "overview": "Housewives Alice and Celine are best friends and neighbors who seem to have it all. However, when a tragic accident shatters the harmony of their lives, guilt, suspicion and paranoia begin to unravel their sisterly bond.",
        "popularity": 36.299,
        "poster_path": "/xscMEP5VsvCLxFvrDQD84biWsLA.jpg",
        "release_date": "2024-04-03",
        "title": "Mothers' Instinct",
        "video": false,
        "vote_average": 6.9,
        "vote_count": 13
      },
      {
        "adult": false,
        "backdrop_path": "/6uKXrsdguwZrtG5BL1wBHvxWs3Z.jpg",
        "genre_ids": [28, 80, 53],
        "id": 557946,
        "original_language": "en",
        "original_title": "Last Looks",
        "overview": "A disgraced ex-cop seeks solace by moving to the woods, but his quiet life comes to an end when a private eye recruits him to investigate the murder of an eccentric TV star's wife.",
        "popularity": 39.673,
        "poster_path": "/eWuvTRuoKrrGVWTtq3QHx13fIDP.jpg",
        "release_date": "2024-05-08",
        "title": "Last Looks",
        "video": false,
        "vote_average": 5.887,
        "vote_count": 279
      },
      {
        "adult": false,
        "backdrop_path": "/a8VgPlIQaX2WfUfYxhF4ItpkTO.jpg",
        "genre_ids": [18, 53],
        "id": 812037,
        "original_language": "fr",
        "original_title": "L’été dernier",
        "overview": "One summer, a French teenager who has been living with his mother in the city moves in with his estranged father’s family in the countryside, where he clashes with his stepmother.",
        "popularity": 44.073,
        "poster_path": "/a94IHwd6t2oXKy5KWTvaEnAs6Ux.jpg",
        "release_date": "2024-04-03",
        "title": "Last Summer",
        "video": false,
        "vote_average": 6,
        "vote_count": 95
      },
      {
        "adult": false,
        "backdrop_path": "/dSyNPeQa4KnWSluU2rP3yansB4P.jpg",
        "genre_ids": [18],
        "id": 1156125,
        "original_language": "ja",
        "original_title": "悪は存在しない",
        "overview": "Takumi and his daughter Hana live in Mizubiki Village, close to Tokyo. One day, the village inhabitants become aware of a plan to build a camping site near Takumi's house offering city residents a comfortable \"escape\" to nature.",
        "popularity": 35.819,
        "poster_path": "/nC7MgPceKAEPWYq6aswrNzG8WAM.jpg",
        "release_date": "2024-03-27",
        "title": "Evil Does Not Exist",
        "video": false,
        "vote_average": 6.858,
        "vote_count": 88
      },
      {
        "adult": false,
        "backdrop_path": "/wPW1cMe2XyeLnm2DNDudoDXVSwt.jpg",
        "genre_ids": [18, 35, 10749],
        "id": 2788,
        "original_language": "en",
        "original_title": "Reality Bites",
        "overview": "A small circle of friends suffering from post-collegiate blues must confront the hard truth about life, love and the pursuit of gainful employment. As they struggle to map out survival guides for the future, the Gen-X quartet soon begins to realize that reality isn't all it's cracked up to be.",
        "popularity": 27.75,
        "poster_path": "/qGDhodtpkpxkrFqokenGNJlzt6w.jpg",
        "release_date": "2024-04-01",
        "title": "Reality Bites",
        "video": false,
        "vote_average": 6.56,
        "vote_count": 688
      }
    ],
    "total_pages": 4,
    "total_results": 75
  }