export const upcoming = {
    "dates": {
      "maximum": "2024-05-29",
      "minimum": "2024-05-08"
    },
    "page": 1,
    "results": [
      {
        "adult": false,
        "backdrop_path": "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
        "genre_ids": [878, 12, 28],
        "id": 653346,
        "original_language": "en",
        "original_title": "Kingdom of the Planet of the Apes",
        "overview": "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
        "popularity": 686.196,
        "poster_path": "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
        "release_date": "2024-05-08",
        "title": "Kingdom of the Planet of the Apes",
        "video": false,
        "vote_average": 7.1,
        "vote_count": 8
      },
      {
        "adult": false,
        "backdrop_path": "/v5XyXZe8FADw8iHupB4L7QOAwH9.jpg",
        "genre_ids": [16, 35, 10751],
        "id": 748783,
        "original_language": "en",
        "original_title": "The Garfield Movie",
        "overview": "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
        "popularity": 757.742,
        "poster_path": "/zK2sFxZcelHJRPVr242rxy5VK4T.jpg",
        "release_date": "2024-05-15",
        "title": "The Garfield Movie",
        "video": false,
        "vote_average": 6.893,
        "vote_count": 15
      },
      {
        "adult": false,
        "backdrop_path": "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
        "genre_ids": [27],
        "id": 938614,
        "original_language": "en",
        "original_title": "Late Night with the Devil",
        "overview": "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
        "popularity": 394.054,
        "poster_path": "/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg",
        "release_date": "2024-05-08",
        "title": "Late Night with the Devil",
        "video": false,
        "vote_average": 7.376,
        "vote_count": 274
      },
      {
        "adult": false,
        "backdrop_path": "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
        "genre_ids": [27, 53, 35],
        "id": 1111873,
        "original_language": "en",
        "original_title": "Abigail",
        "overview": "After a group of would-be criminals kidnap the 12 year old ballerina daughter of a powerful underworld figure, all they have to do to collect a $50 million ransom is watch the girl overnight. In an isolated mansion, the captors start to dwindle, one by one, and they discover, to their mounting horror, that they’re locked inside with no normal little girl.",
        "popularity": 269.968,
        "poster_path": "/5Uq8P6MPj9Ppsns5t82AiCiUaWE.jpg",
        "release_date": "2024-05-15",
        "title": "Abigail",
        "video": false,
        "vote_average": 6.878,
        "vote_count": 86
      },
      {
        "adult": false,
        "backdrop_path": "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
        "genre_ids": [28, 53, 80],
        "id": 560016,
        "original_language": "en",
        "original_title": "Monkey Man",
        "overview": "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
        "popularity": 210.112,
        "poster_path": "/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg",
        "release_date": "2024-05-29",
        "title": "Monkey Man",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 294
      },
      {
        "adult": false,
        "backdrop_path": "/zj13HSGkT7EIRwUKnXrurgkQ1qc.jpg",
        "genre_ids": [878, 28, 12],
        "id": 786892,
        "original_language": "en",
        "original_title": "Furiosa: A Mad Max Saga",
        "overview": "As the world falls, young Furiosa is snatched from the Green Place of Many Mothers into the hands of a great biker horde led by the warlord Dementus. Sweeping through the wasteland, they encounter the citadel presided over by Immortan Joe. The two tyrants wage war for dominance, and Furiosa must survive many trials as she puts together the means to find her way home.",
        "popularity": 168.945,
        "poster_path": "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
        "release_date": "2024-05-22",
        "title": "Furiosa: A Mad Max Saga",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/vpWVeIMNi0Np5shuKFE3QkneiTt.jpg",
        "genre_ids": [35, 14, 10751],
        "id": 639720,
        "original_language": "en",
        "original_title": "IF",
        "overview": "A girl discovers she can see everyone's imaginary friends and embarks on a magical adventure to reconnect forgotten IFs with their kids.",
        "popularity": 121.831,
        "poster_path": "/kLOopsjpSX1Wb1h8Vg57t7YEwD6.jpg",
        "release_date": "2024-05-15",
        "title": "IF",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/okXIAgFc2U6jf4uZrivhwEu7vbW.jpg",
        "genre_ids": [35, 14],
        "id": 823482,
        "original_language": "en",
        "original_title": "Dream Scenario",
        "overview": "Hapless family man Paul Matthews finds his life turned upside down when millions of strangers suddenly start seeing him in their dreams. But when his nighttime appearances take a nightmarish turn, Paul is forced to navigate his newfound stardom.",
        "popularity": 95.684,
        "poster_path": "/eMaAi8wTI5wON8pp33w3BDuGyZ8.jpg",
        "release_date": "2024-05-29",
        "title": "Dream Scenario",
        "video": false,
        "vote_average": 6.744,
        "vote_count": 583
      },
      {
        "adult": false,
        "backdrop_path": "/nQPwP1uonkooEn4oEpDU0NGW8vH.jpg",
        "genre_ids": [35, 80, 28],
        "id": 974635,
        "original_language": "en",
        "original_title": "Hit Man",
        "overview": "A mild-mannered professor moonlighting as a fake contract killer sparks a chain reaction of trouble when he falls for a client.",
        "popularity": 56.42,
        "poster_path": "/1126gjlBf4hTm9Sgf0ox3LGVEBt.jpg",
        "release_date": "2024-05-24",
        "title": "Hit Man",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/6uKXrsdguwZrtG5BL1wBHvxWs3Z.jpg",
        "genre_ids": [28, 80, 53],
        "id": 557946,
        "original_language": "en",
        "original_title": "Last Looks",
        "overview": "A disgraced ex-cop seeks solace by moving to the woods, but his quiet life comes to an end when a private eye recruits him to investigate the murder of an eccentric TV star's wife.",
        "popularity": 39.673,
        "poster_path": "/eWuvTRuoKrrGVWTtq3QHx13fIDP.jpg",
        "release_date": "2024-05-08",
        "title": "Last Looks",
        "video": false,
        "vote_average": 5.887,
        "vote_count": 279
      },
      {
        "adult": false,
        "backdrop_path": "/cZmOrIOkJ2SNfVdiO85dUbOAYnL.jpg",
        "genre_ids": [16, 35, 18],
        "id": 1012201,
        "original_language": "ja",
        "original_title": "劇場版ハイキュー!! ゴミ捨て場の決戦",
        "overview": "Shoyo Hinata joins Karasuno High's volleyball club to be like his idol, a former Karasuno player known as the \"Little Giant.\" But, Hinata soon finds that he must team up with his middle school nemesis, Tobio Kageyama. Their clashing styles turn into a surprising weapon, but can they beat their rival Nekoma High in the highly anticipated \"Dumpster Battle,\" the long awaited ultimate showdown between two opposing underdog teams?",
        "popularity": 54.554,
        "poster_path": "/ntRU0OA4etGGiMMmH1Yw0bnaMdW.jpg",
        "release_date": "2024-05-15",
        "title": "HAIKYU!! The Dumpster Battle",
        "video": false,
        "vote_average": 8.7,
        "vote_count": 8
      },
      {
        "adult": false,
        "backdrop_path": "/hY97iRKr2t44lbX2GHRhfK5CVC7.jpg",
        "genre_ids": [99],
        "id": 1004663,
        "original_language": "en",
        "original_title": "All the Beauty and the Bloodshed",
        "overview": "The life of internationally renowned artist and activist Nan Goldin is told through her slideshows, intimate interviews, ground-breaking photography, and rare footage of her personal fight to hold the Sackler family accountable for the overdose crisis.",
        "popularity": 32.384,
        "poster_path": "/cvO51xxtIUHc5w5ZgFsigiFaUaO.jpg",
        "release_date": "2024-05-15",
        "title": "All the Beauty and the Bloodshed",
        "video": false,
        "vote_average": 7.426,
        "vote_count": 121
      },
      {
        "adult": false,
        "backdrop_path": "/aWcqE8wGN8Gv4VSPAGCqTFYy7aC.jpg",
        "genre_ids": [35],
        "id": 965791,
        "original_language": "fr",
        "original_title": "Une année difficile",
        "overview": "Compulsive spenders Albert and Bruno are in debt up to their necks. While seeking help from community workers to get their lives back on track, they run into a group of young green activists. Lured by the free beer and snacks rather than by the ideals of eco-activists, Albert and Bruno find themselves joining the movement without much conviction.",
        "popularity": 18.478,
        "poster_path": "/calbXqzHVxfKlmtcwnSdCMW4owN.jpg",
        "release_date": "2024-05-15",
        "title": "A Difficult Year",
        "video": false,
        "vote_average": 6.1,
        "vote_count": 167
      },
      {
        "adult": false,
        "backdrop_path": "/v6zPAMPaHs2fhdYyvi2rMJQI3YD.jpg",
        "genre_ids": [35],
        "id": 925263,
        "original_language": "it",
        "original_title": "Il sol dell'avvenire",
        "overview": "An old film director unhappy with the movie he's shooting about a Hungarian circus stranded in Rome during the 1956 anti-Soviet uprising faces divorce from his producer wife and other problems.",
        "popularity": 18.168,
        "poster_path": "/rN5ExiIpjHGAcm5mN4RsVzi0y1e.jpg",
        "release_date": "2024-05-29",
        "title": "A Brighter Tomorrow",
        "video": false,
        "vote_average": 7.079,
        "vote_count": 258
      },
      {
        "adult": false,
        "backdrop_path": "/rZ4LvgRY9ExeHRh2uppIkTM6Oc4.jpg",
        "genre_ids": [10751, 12],
        "id": 654910,
        "original_language": "en",
        "original_title": "The Tiger's Nest",
        "overview": "In the valleys of the Himalayas, an orphan boy saves a Bengal tiger cub from the ruthless poachers who killed the tiger's mother. Together they set out in the Himalayan mountains to the Taktsang monastery in Bhutan known as \"The Tiger's Nest\" where Buddhist monks took refuge after the 1950 Chinese invasion of Tibet and protect the big cats. A new great film for the whole family that talks about the importance of defending animals through the story of the friendship between two orphans, a tiger cub and a child, in a tale of brotherhood and the discovery of life.",
        "popularity": 11.955,
        "poster_path": "/1oZFVPrdMbmEchJkGWr9T5mVeZ7.jpg",
        "release_date": "2024-05-16",
        "title": "The Tiger's Nest",
        "video": false,
        "vote_average": 6.6,
        "vote_count": 54
      },
      {
        "adult": false,
        "backdrop_path": "/zuIvu89BpYREc42OKzWyXzANNAQ.jpg",
        "genre_ids": [10749],
        "id": 1188258,
        "original_language": "ja",
        "original_title": "青春18x2 君へと続く道",
        "overview": "A journey begins to trace the memory of a first love, transcending the time and borders between Japan and Taiwan over a period of 18 years.",
        "popularity": 15.225,
        "poster_path": "/nt68WTFgtZdLBwpLBF2q7GFq5Fw.jpg",
        "release_date": "2024-05-22",
        "title": "18×2 Beyond Youthful Days",
        "video": false,
        "vote_average": 8.2,
        "vote_count": 2
      },
      {
        "adult": false,
        "backdrop_path": "/9ZcJT3plQQPnYqCRkTBbOSksVX8.jpg",
        "genre_ids": [53, 9648],
        "id": 743815,
        "original_language": "ko",
        "original_title": "그녀가 죽었다",
        "overview": "Realtor Jung-tae’s hobby is sneaking into strangers’ homes and peeping into their lives. One day, an unfamiliar face in the area grabs his attention – an Instagram star, So-ra. Miraculously, So-ra leaves her house key at Jung-tae’s agency and Jung-tae visits her home whenever he can, thrilled and excited. Like any other day, Jung-tae makes another visit and finds what he hadn’t expected: the dead body of So-ra. Jung-tae is shocked and he can’t call the police and report. But when he returns few hours later with a client… So-ra’s dead body is gone! Days later, Jung-tae receives a red note saying ‘It was you, right?’. Even worse, all evidences say that Jung-tae is the criminal. Can he find the real killer and clear his name?",
        "popularity": 9.207,
        "poster_path": "/p6goyFC8mDyUFow1ipsghfSULo9.jpg",
        "release_date": "2024-05-15",
        "title": "Following",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/s9GMagopY0MrXaAk4zqsDtVjT9Y.jpg",
        "genre_ids": [18, 10751],
        "id": 1075966,
        "original_language": "no",
        "original_title": "Dancing Queen",
        "overview": "12-year-old Mina freaks out when famous hip-hop dancer ED Win moves to town and starts at her school. Mina falls in love and when ED announces he's forming a new dance group for a dance competition in town, Mina decides to audition. The only problem is that she can't dance.",
        "popularity": 6.473,
        "poster_path": "/iFeyjpo8VyfqLuzjK8yI51DellS.jpg",
        "release_date": "2024-05-29",
        "title": "Dancing Queen",
        "video": false,
        "vote_average": 6.2,
        "vote_count": 2
      },
      {
        "adult": false,
        "backdrop_path": "/vTevRxMGwZpsKEpPmSCLYY3desv.jpg",
        "genre_ids": [878],
        "id": 763223,
        "original_language": "ja",
        "original_title": "８日で死んだ怪獣の１２日の物語 -劇場版-",
        "overview": "An actor who has lost his job due to the coronavirus buys capsule monsters online and begins to raise them.",
        "popularity": 7.556,
        "poster_path": "/pu7nGJELBGtJJIT7GZ7nrfimbK6.jpg",
        "release_date": "2024-05-16",
        "title": "The 12 Day Tale of the Monster that Died in 8",
        "video": false,
        "vote_average": 5.6,
        "vote_count": 5
      },
      {
        "adult": false,
        "backdrop_path": "/mkYWWzV34Ynyg2jgSRbZvTZEgO1.jpg",
        "genre_ids": [18],
        "id": 1106527,
        "original_language": "ko",
        "original_title": "미지수",
        "overview": "Wooju brings a corpse to his lover Jisu's place. At that time, Giwan had a nightmare floating in space. He searches for articles about rocket launching every day. Uju brings his mother Sinae's dead body. As the rocket launch count begins, Giwan swells with anticipation. And Jisu receives a phone call from the dead Sinae.",
        "popularity": 6.866,
        "poster_path": "/yiX5ikg429FFSfjemd91r0Ixhwi.jpg",
        "release_date": "2024-05-08",
        "title": "Unknown",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      }
    ],
    "total_pages": 2,
    "total_results": 30
  }